### PR TITLE
Merge changes from MehrCurry

### PR DESCRIPTION
**Pull request by tmaier**
@MehrCurry has some nice changes in his/her repository.

- Allow to set `ci_runner_instance_name`
- increase disk size
- Use VM type `e2-micro`, which is more powerful and a bit cheaper

### CODE REVIEW

**Comment by brettch** [comment]
The changes look great!  Thanks for the PR.

**Comment by tmaier** [comment]
Thanks! You can find interesting changes in the [Network graph](https://github.com/digio/terraform-google-gitlab-runner/network)

**Comment by MehrCurry** [comment]
Sorry, i forgot to re-contribute my changes. Glad @tmaier took over. Thanks for the great work so far.

**Comment by brettch** [comment]
Agree, @tmaier.  The [Network graph](https://github.com/digio/terraform-google-gitlab-runner/network) does look interesting.  I'm hoping to trawl through them at some point.  It just hasn't made it to the top of the list yet :-)

**Pull request merged**
